INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(  --CODE
  PARENT_ID,
  CHILD_ID,
  IS_PARENT,
  IS_CHILD,
  PARENT_ITEM_TYPE,
  CHILD_ITEM_TYPE,
  PARAM_NAME,
  PARAM_VALUE,
  INDEX_SEQ)
VALUES (-1, 12, 'Y', 'N','SEED','ACTIVITY_TYPE', 'PRODUCT_TYPE', 'Product Type', 0);

 
 INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (12, 1, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'PRODUCT_TYPE', 'Wire', 1);
   
 
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (12, 2, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'PRODUCT_TYPE', 'ACH RDFI', 2);
  

INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(  --CODE
  PARENT_ID,
  CHILD_ID,
  IS_PARENT,
  IS_CHILD,
  PARENT_ITEM_TYPE,
  CHILD_ITEM_TYPE,
  PARAM_NAME,
  PARAM_VALUE,
  INDEX_SEQ)
VALUES (-1, 13, 'Y', 'N','SEED','ACTIVITY_TYPE', 'TYPE_WIRE_TRANSFER', 'Type of Wire Transfer(for Wires only)', 0);


INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF( --VALID VALUE
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (13, 1, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'TYPE_WIRE_TRANSFER', 'Domestic', 1);
   
 
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF( --VALID VALUE
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (13, 2, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'TYPE_WIRE_TRANSFER', 'International US$', 2);
   

INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF( --VALID VALUE
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (13, 3, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'TYPE_WIRE_TRANSFER', 'FX-Non US$', 3);  


 
   INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(  --CODE
  PARENT_ID,
  CHILD_ID,
  IS_PARENT,
  IS_CHILD,
  PARENT_ITEM_TYPE,
  CHILD_ITEM_TYPE,
  PARAM_NAME,
  PARAM_VALUE,
  INDEX_SEQ)
VALUES (-1, 14, 'Y', 'N','SEED','ACTIVITY_TYPE', 'FUNDS_FRB', 'Did Funds leave FRB?', 0);

 
 INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (14, 1, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'FUNDS_FRB', 'Yes', 1);
   
 
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (14, 2, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'FUNDS_FRB', 'No', 2);
  
  

INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (14, 3, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'FUNDS_FRB', 'Unknown', 3);
  
 
   INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(  --CODE
  PARENT_ID,
  CHILD_ID,
  IS_PARENT,
  IS_CHILD,
  PARENT_ITEM_TYPE,
  CHILD_ITEM_TYPE,
  PARAM_NAME,
  PARAM_VALUE,
  INDEX_SEQ)
VALUES (-1, 15, 'Y', 'N','SEED','ACTIVITY_TYPE', 'FUNDS_FRB', 'DID THE CLIENT INITIATE THE TRANSACTION?', 0);

 
 INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (15, 1, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'FUNDS_FRB', 'Yes', 1);
   
 
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (15, 2, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'FUNDS_FRB', 'No', 2);
  
  

INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (15, 3, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'FUNDS_FRB', 'Unknown', 3);


   INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(  --CODE
  PARENT_ID,
  CHILD_ID,
  IS_PARENT,
  IS_CHILD,
  PARENT_ITEM_TYPE,
  CHILD_ITEM_TYPE,
  PARAM_NAME,
  PARAM_VALUE,
  INDEX_SEQ)
VALUES (-1, 16, 'Y', 'N','SEED','ACTIVITY_TYPE', 'EMP_INITIAL', 'Employee Initials', 0);

 
 INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (16, 1, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'EMP_INITIAL', 'Online', 1);
   
 
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (16, 2, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'EMP_INITIAL', 'Email', 2);
  
  

INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (16, 3, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'EMP_INITIAL', 'Fax', 3);

  

INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (16, 4, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'EMP_INITIAL', 'In Person', 3);  
   

   
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(  --CODE
  PARENT_ID,
  CHILD_ID,
  IS_PARENT,
  IS_CHILD,
  PARENT_ITEM_TYPE,
  CHILD_ITEM_TYPE,
  PARAM_NAME,
  PARAM_VALUE,
  INDEX_SEQ)
VALUES (-1, 17, 'Y', 'N','SEED','ACTIVITY_TYPE', 'TRANSACTION_INITIATED', 'HOW WAS THE TRANSACTION INITIATED?', 0);

 
 INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (17, 1, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'TRANSACTION_INITIATED', 'Yes', 1);
   
 
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (17, 2, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'TRANSACTION_INITIATED', 'No', 2);
  
  

INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (17, 3, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'TRANSACTION_INITIATED', 'Unknown', 3);
