CREATE TABLE FRAUD_INTAKE_LOOKUPS (
	LOOKUP_ID BIGINT IDENTITY (1,1) NOT NULL,
	LOOKUP_TYPE VARCHAR(200) NOT NULL, 
	LOOKUP_CODE VARCHAR(200) NOT NULL, 
	LOOKUP_MEANING VARCHAR(200) NOT NULL, 
	LOOKUP_VALUE VARCHAR(200) NOT NULL,  
	LOOKUP_VALUE1 VARCHAR(200)  NULL, 
	LOOKUP_VALUE2 VARCHAR(200) NULL, 
	IS_ENABLED VARCHAR(2) NOT NULL	
);

--CUSTOMER LOOKUPS

INSERT INTO FRAUD_INTAKE_LOOKUPS
(LOOKUP_TYPE,LOOKUP_CODE, LOOKUP_MEANING, LOOKUP_VALUE, IS_ENABLED)
 VALUES(
 'CUSTOMER', 'FULLNAME_SUBJECT', 'Full Name of Subject', 'xyz', 'Y'
);

INSERT INTO FRAUD_INTAKE_LOOKUPS
(LOOKUP_TYPE,LOOKUP_CODE, LOOKUP_MEANING, LOOKUP_VALUE, IS_ENABLED)
 VALUES(
 'CUSTOMER', 'CUSTOMER_KEY', 'Customer Key', 'xyz', 'Y'
);

INSERT INTO FRAUD_INTAKE_LOOKUPS
(LOOKUP_TYPE,LOOKUP_CODE, LOOKUP_MEANING, LOOKUP_VALUE, IS_ENABLED)
 VALUES(
 'CUSTOMER', 'ACCOUNT_NUMBER', 'Account Number', 'xyz', 'Y'
);

INSERT INTO FRAUD_INTAKE_LOOKUPS
(LOOKUP_TYPE,LOOKUP_CODE, LOOKUP_MEANING, LOOKUP_VALUE, IS_ENABLED)
 VALUES(
 'CUSTOMER', 'ACCOUNT_TITLE', 'Account Title', 'xyz', 'Y'
);

INSERT INTO FRAUD_INTAKE_LOOKUPS
(LOOKUP_TYPE,LOOKUP_CODE, LOOKUP_MEANING, LOOKUP_VALUE, IS_ENABLED)
 VALUES(
 'CUSTOMER', 'ACCOUNT_TYPE', 'Account Type', 'xyz', 'Y'
);


--EMPLOYEE LOOKUPS

INSERT INTO FRAUD_INTAKE_LOOKUPS
(LOOKUP_TYPE,LOOKUP_CODE, LOOKUP_MEANING, LOOKUP_VALUE, IS_ENABLED)
 VALUES(
 'EMPLOYEE', 'REPORTED_BY', 'Reported By', 'xyz', 'Y'
);

INSERT INTO FRAUD_INTAKE_LOOKUPS
(LOOKUP_TYPE,LOOKUP_CODE, LOOKUP_MEANING, LOOKUP_VALUE, IS_ENABLED)
 VALUES(
 'EMPLOYEE', 'REFERRAL DEPARTMENT', 'Referral Department', 'xyz', 'Y'
);

INSERT INTO FRAUD_INTAKE_LOOKUPS
(LOOKUP_TYPE,LOOKUP_CODE, LOOKUP_MEANING, LOOKUP_VALUE, IS_ENABLED)
 VALUES(
 'EMPLOYEE', 'NETWORK_ID', 'Network Id', 'xyz', 'Y'
);

INSERT INTO FRAUD_INTAKE_LOOKUPS
(LOOKUP_TYPE,LOOKUP_CODE, LOOKUP_MEANING, LOOKUP_VALUE, IS_ENABLED)
 VALUES(
 'EMPLOYEE', 'OFFICE_NAME', 'Office Name', 'xyz', 'Y'
);

INSERT INTO FRAUD_INTAKE_LOOKUPS
(LOOKUP_TYPE,LOOKUP_CODE, LOOKUP_MEANING, LOOKUP_VALUE, IS_ENABLED)
 VALUES(
 'EMPLOYEE', 'SUBJECT_DEP', 'Subject Department', 'xyz', 'Y'
);

INSERT INTO FRAUD_INTAKE_LOOKUPS
(LOOKUP_TYPE,LOOKUP_CODE, LOOKUP_MEANING, LOOKUP_VALUE, IS_ENABLED)
 VALUES(
 'EMPLOYEE', 'REGION', 'Region', 'xyz', 'Y'
);

INSERT INTO FRAUD_INTAKE_LOOKUPS
(LOOKUP_TYPE,LOOKUP_CODE, LOOKUP_MEANING, LOOKUP_VALUE, IS_ENABLED)
 VALUES(
 'EMPLOYEE', 'MANAGERS_NAME', 'Manager's Name', 'xyz', 'Y'
);

INSERT INTO FRAUD_INTAKE_LOOKUPS
(LOOKUP_TYPE,LOOKUP_CODE, LOOKUP_MEANING, LOOKUP_VALUE, IS_ENABLED)
 VALUES(
 'EMPLOYEE', 'HR_BUSSINESS_PARTNER_NAME', 'Hr Bussiness Parter Name', 'xyz', 'Y'
);

INSERT INTO FRAUD_INTAKE_LOOKUPS
(LOOKUP_TYPE,LOOKUP_CODE, LOOKUP_MEANING, LOOKUP_VALUE, IS_ENABLED)
 VALUES(
 'EMPLOYEE', 'EMPLOYEE_INITIALS', 'Employee Initials', 'xyz', 'Y'
);