

CREATE TABLE SAMPLE_DATA.dbo.FRAUD_INTAKE_MASTER (
  FRAUD_INTAKE_ID bigint IDENTITY (1, 1) NOT NULL PRIMARY KEY,
  IS_SEED  varchar(4) NULL,
  IS_ENABLED varchar(4) NULL,
  AUDIT_ID varchar(200) NULL,
  CREATION_DATE datetime NOT NULL,
  ATTRIBUTE1 varchar(100) NULL,
  ATTRIBUTE2 varchar(100) NULL,
  ATTRIBUTE3 varchar(100) NULL,
  ATTRIBUTE4 varchar(100) NULL,
  ATTRIBUTE5 varchar(100) NULL
);

CREATE TABLE SAMPLE_DATA.dbo.FRAUD_INTAKE_REF (
  INTAKE_REF_ID bigint IDENTITY (1, 1) NOT NULL PRIMARY KEY,
  PARENT_ID bigint NULL,
  CHILD_ID bigint NULL,
  IS_PARENT varchar(4) NULL,
  IS_CHILD varchar(4) NULL,
  PARENT_ITEM_TYPE varchar(50) NULL,
  CHILD_ITEM_TYPE varchar(50) NULL,
  PARAM_NAME varchar(100) NULL,
  PARAM_VALUE varchar(200) NULL,
  PARAM_VALUE1 varchar(200) NULL,
  PARAM_VALUE2 varchar(200) NULL,
  PARAM_VALUE3 varchar(200) NULL,
  PARAM_VALUE4 varchar(200) NULL,
  PARAM_VALUE5 varchar(200) NULL,
  IS_MULTI varchar(4) NULL,
  INDEX_SEQ tinyint NULL,
  IS_SEED varchar(4) NULL,
  IS_ENABLED varchar(4) NULL
);

CREATE TABLE SAMPLE_DATA.dbo.FRAUD_INTAKE_FILES (
  INTAKE_FILE_ID bigint IDENTITY (1, 1) NOT NULL PRIMARY KEY,
  INTAKE_REF_ID bigint NULL,
  FILE_NAME varchar(200) NULL,
  FILE_CONTENT varbinary(2000),
  ATTRIBUTE1 varchar(100) NULL,
  ATTRIBUTE2 varchar(100) NULL,
  ATTRIBUTE3 varchar(100) NULL,
  ATTRIBUTE4 varchar(100) NULL,
  ATTRIBUTE5 varchar(100) NULL
);



INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_MASTER( IS_SEED, IS_ENABLED, AUDIT_ID, CREATION_DATE) 
VALUES ('Y', 'Y', -1, GETDATE());


 INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(  --CODE
  PARENT_ID,
  CHILD_ID,
  IS_PARENT,
  IS_CHILD,
  PARENT_ITEM_TYPE,
  CHILD_ITEM_TYPE,
  PARAM_NAME,
  PARAM_VALUE,
  INDEX_SEQ)
VALUES (-1, 1, 'Y', 'N','SEED','MASTER', 'REPORT_TYPE', 'Tyope of Report', 0);

 
 INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (1, 1, 'N', 'Y',
   'SEED',          'MASTER',         'REPORT_TYPE', 'Report a Fraud Event', 1);
   
 
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (1, 2, 'N', 'Y',
   'SEED',          'MASTER',         'REPORT_TYPE', 'Fraud Inquiry', 2);
   

INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (1, 3, 'N', 'Y',
   'SEED',          'MASTER',         'REPORT_TYPE', 'Internal Incident', 3);  



 
 INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(  --CODE
  PARENT_ID,
  CHILD_ID,
  IS_PARENT,
  IS_CHILD,
  PARENT_ITEM_TYPE,
  CHILD_ITEM_TYPE,
  PARAM_NAME,
  PARAM_VALUE,
  INDEX_SEQ)
VALUES (-1, 2, 'Y', 'N','SEED','MASTER', 'FRAUD_TYPE_CD', 'Tyope of Fraud', 0);

 
 INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (2, 1, 'N', 'Y',
   'SEED',          'MASTER',         'FRAUD_TYPE_CD', 'Transactional', 1);
   
 
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (2, 2, 'N', 'Y',
   'SEED',          'MASTER',         'FRAUD_TYPE_CD', 'Non Transactional', 2);
   



 
  INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(  --CODE
  PARENT_ID,
  CHILD_ID,
  IS_PARENT,
  IS_CHILD,
  PARENT_ITEM_TYPE,
  CHILD_ITEM_TYPE,
  PARAM_NAME,
  PARAM_VALUE,
  INDEX_SEQ)
VALUES (-1, 3, 'Y', 'N','SEED','MASTER', 'SUBJECT_TYPE_CD', 'Subject Type', 0);

 
 INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (3, 1, 'N', 'Y',
   'SEED',          'MASTER',         'SUBJECT_TYPE_CD', 'Client', 1);
   
 
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (3, 2, 'N', 'Y',
   'SEED',          'MASTER',         'SUBJECT_TYPE_CD', 'Former Client', 2);
  
  

INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (3, 3, 'N', 'Y',
   'SEED',          'MASTER',         'SUBJECT_TYPE_CD', 'Prospective Client', 3);
  

INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (3, 4, 'N', 'Y',
   'SEED',          'MASTER',         'SUBJECT_TYPE_CD', 'Non - Client', 4);
  
  

INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (3, 5, 'N', 'Y',
   'SEED',          'MASTER',         'SUBJECT_TYPE_CD', 'Unknown', 5);
  

INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (3, 6, 'N', 'Y',
   'SEED',          'MASTER',         'SUBJECT_TYPE_CD', 'NA', 6);
   




  INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(  --CODE
  PARENT_ID,
  CHILD_ID,
  IS_PARENT,
  IS_CHILD,
  PARENT_ITEM_TYPE,
  CHILD_ITEM_TYPE,
  PARAM_NAME,
  PARAM_VALUE,
  INDEX_SEQ)
VALUES (-1, 4, 'Y', 'N','SEED','MASTER', 'CUST_TYPE_CD', 'Client Type', 0);

 
 INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (4, 1, 'N', 'Y',
   'SEED',          'MASTER',         'CUST_TYPE_CD', 'Consumer', 1);
   
 
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (4, 2, 'N', 'Y',
   'SEED',          'MASTER',         'CUST_TYPE_CD', 'Business', 2);
  
  


 
 
   
  INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(  --CODE
  PARENT_ID,
  CHILD_ID,
  IS_PARENT,
  IS_CHILD,
  PARENT_ITEM_TYPE,
  CHILD_ITEM_TYPE,
  PARAM_NAME,
  PARAM_VALUE,
  INDEX_SEQ)
VALUES (-1, 5, 'Y', 'N','SEED','MASTER', 'ACCOUNT_TAKEOVER_CD', 'DOES THIS REFERRAL INVOLVE AN ACCOUNT TAKEOVER?', 0);

 
 INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (5, 1, 'N', 'Y',
   'SEED',          'MASTER',         'ACCOUNT_TAKEOVER_CD', 'Yes', 1);
   
 
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (5, 2, 'N', 'Y',
   'SEED',          'MASTER',         'ACCOUNT_TAKEOVER_CD', 'No', 2);
  
  



 
   
  INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(  --CODE
  PARENT_ID,
  CHILD_ID,
  IS_PARENT,
  IS_CHILD,
  PARENT_ITEM_TYPE,
  CHILD_ITEM_TYPE,
  PARAM_NAME,
  PARAM_VALUE,
  INDEX_SEQ)
VALUES (-1, 6, 'Y', 'N','SEED','MASTER', 'EXPLOITATION_CD', 'DOES THIS REFERRAL INVOLVE POTENTIAL ELDER FINANCIAL EXPLOITATION?', 0);

 
 INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (6, 1, 'N', 'Y',
   'SEED',          'MASTER',         'EXPLOITATION_CD', 'Yes', 1);
   
 
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (6, 2, 'N', 'Y',
   'SEED',          'MASTER',         'EXPLOITATION_CD', 'No', 2);
   
   







 
   
  INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(  --CODE
  PARENT_ID,
  CHILD_ID,
  IS_PARENT,
  IS_CHILD,
  PARENT_ITEM_TYPE,
  CHILD_ITEM_TYPE,
  PARAM_NAME,
  PARAM_VALUE,
  INDEX_SEQ)
VALUES (-1, 7, 'Y', 'N','SEED','MASTER', 'IDENTITY_THEFT_CD', 'Is this referral related to Identity Theft?', 0);

 
 INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (7, 1, 'N', 'Y',
   'SEED',          'MASTER',         'IDENTITY_THEFT_CD', 'Yes', 1);
   
 
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (7, 2, 'N', 'Y',
   'SEED',          'MASTER',         'IDENTITY_THEFT_CD', 'No', 2);
   
   




  INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(  --CODE
  PARENT_ID,
  CHILD_ID,
  IS_PARENT,
  IS_CHILD,
  PARENT_ITEM_TYPE,
  CHILD_ITEM_TYPE,
  PARAM_NAME,
  PARAM_VALUE,
  INDEX_SEQ)
VALUES (-1, 8, 'Y', 'N','SEED','MASTER', 'CYBER_EVENT_CD', 'DOES THIS REFERRAL INVOLVE A SIGNIFICANT ENTERPRISE CYBER EVENT?', 0);

 
 INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (8, 1, 'N', 'Y',
   'SEED',          'MASTER',         'CYBER_EVENT_CD', 'Yes', 1);
   
 
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (8, 2, 'N', 'Y',
   'SEED',          'MASTER',         'CYBER_EVENT_CD', 'No', 2);
   
   






  INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(  --CODE
  PARENT_ID,
  CHILD_ID,
  IS_PARENT,
  IS_CHILD,
  PARENT_ITEM_TYPE,
  CHILD_ITEM_TYPE,
  PARAM_NAME,
  PARAM_VALUE,
  INDEX_SEQ)
VALUES (-1, 9, 'Y', 'N','SEED','MASTER', 'ANONYMOUS_CD', 'DO YOU WANT TO REMAIN ANONYMOUS?', 0);

 
 INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (9, 1, 'N', 'Y',
   'SEED',          'MASTER',         'ANONYMOUS_CD', 'Yes', 1);
   
 
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (9, 2, 'N', 'Y',
   'SEED',          'MASTER',         'ANONYMOUS_CD', 'No', 2);
   
   





  INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(  --CODE
  PARENT_ID,
  CHILD_ID,
  IS_PARENT,
  IS_CHILD,
  PARENT_ITEM_TYPE,
  CHILD_ITEM_TYPE,
  PARAM_NAME,
  PARAM_VALUE,
  INDEX_SEQ)
VALUES (-1, 10, 'Y', 'N','SEED','MASTER', 'INCIDENT_ELSE_CD', 'DID YOU REPORT THIS INCIDENT SOMEHWERE ELSE?', 0);

 
 INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (10, 1, 'N', 'Y',
   'SEED',          'MASTER',         'INCIDENT_ELSE_CD', 'Yes', 1);
   
 
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (10, 2, 'N', 'Y',
   'SEED',          'MASTER',         'INCIDENT_ELSE_CD', 'No', 2);


INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(  --CODE
  PARENT_ID,
  CHILD_ID,
  IS_PARENT,
  IS_CHILD,
  PARENT_ITEM_TYPE,
  CHILD_ITEM_TYPE,
  PARAM_NAME,
  PARAM_VALUE,
  INDEX_SEQ)
VALUES (-1, 12, 'Y', 'N','SEED','ACTIVITY_TYPE', 'PRODUCT_TYPE', 'Product Type', 0);

 
 INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (12, 1, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'PRODUCT_TYPE', 'Wire', 1);
   
 
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (12, 2, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'PRODUCT_TYPE', 'ACH RDFI', 2);
  

INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(  --CODE
  PARENT_ID,
  CHILD_ID,
  IS_PARENT,
  IS_CHILD,
  PARENT_ITEM_TYPE,
  CHILD_ITEM_TYPE,
  PARAM_NAME,
  PARAM_VALUE,
  INDEX_SEQ)
VALUES (-1, 13, 'Y', 'N','SEED','ACTIVITY_TYPE', 'TYPE_WIRE_TRANSFER', 'Type of Wire Transfer(for Wires only)', 0);


INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF( --VALID VALUE
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (13, 1, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'TYPE_WIRE_TRANSFER', 'Domestic', 1);
   
 
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF( --VALID VALUE
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (13, 2, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'TYPE_WIRE_TRANSFER', 'International US$', 2);
   

INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF( --VALID VALUE
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (13, 3, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'TYPE_WIRE_TRANSFER', 'FX-Non US$', 3);  


 
   INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(  --CODE
  PARENT_ID,
  CHILD_ID,
  IS_PARENT,
  IS_CHILD,
  PARENT_ITEM_TYPE,
  CHILD_ITEM_TYPE,
  PARAM_NAME,
  PARAM_VALUE,
  INDEX_SEQ)
VALUES (-1, 14, 'Y', 'N','SEED','ACTIVITY_TYPE', 'FUNDS_FRB', 'Did Funds leave FRB?', 0);

 
 INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (14, 1, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'FUNDS_FRB', 'Yes', 1);
   
 
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (14, 2, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'FUNDS_FRB', 'No', 2);
  
  

INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (14, 3, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'FUNDS_FRB', 'Unknown', 3);
  
 
   INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(  --CODE
  PARENT_ID,
  CHILD_ID,
  IS_PARENT,
  IS_CHILD,
  PARENT_ITEM_TYPE,
  CHILD_ITEM_TYPE,
  PARAM_NAME,
  PARAM_VALUE,
  INDEX_SEQ)
VALUES (-1, 15, 'Y', 'N','SEED','ACTIVITY_TYPE', 'FUNDS_FRB', 'DID THE CLIENT INITIATE THE TRANSACTION?', 0);

 
 INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (15, 1, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'FUNDS_FRB', 'Yes', 1);
   
 
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (15, 2, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'FUNDS_FRB', 'No', 2);
  
  

INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (15, 3, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'FUNDS_FRB', 'Unknown', 3);


   INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(  --CODE
  PARENT_ID,
  CHILD_ID,
  IS_PARENT,
  IS_CHILD,
  PARENT_ITEM_TYPE,
  CHILD_ITEM_TYPE,
  PARAM_NAME,
  PARAM_VALUE,
  INDEX_SEQ)
VALUES (-1, 16, 'Y', 'N','SEED','ACTIVITY_TYPE', 'EMP_INITIAL', 'Employee Initials', 0);

 
 INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (16, 1, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'EMP_INITIAL', 'Online', 1);
   
 
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (16, 2, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'EMP_INITIAL', 'Email', 2);
  
  

INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (16, 3, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'EMP_INITIAL', 'Fax', 3);

  

INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (16, 4, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'EMP_INITIAL', 'In Person', 3);  
   

   
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(  --CODE
  PARENT_ID,
  CHILD_ID,
  IS_PARENT,
  IS_CHILD,
  PARENT_ITEM_TYPE,
  CHILD_ITEM_TYPE,
  PARAM_NAME,
  PARAM_VALUE,
  INDEX_SEQ)
VALUES (-1, 17, 'Y', 'N','SEED','ACTIVITY_TYPE', 'FUNDS_FRB', 'HOW WAS THE TRANSACTION INITIATED?', 0);

 
 INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (17, 1, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'FUNDS_FRB', 'Yes', 1);
   
 
INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (17, 2, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'FUNDS_FRB', 'No', 2);
  
  

INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_REF(
  PARENT_ID,  CHILD_ID,  IS_PARENT,  IS_CHILD, 
  PARENT_ITEM_TYPE,  CHILD_ITEM_TYPE,  PARAM_NAME,          PARAM_VALUE,  INDEX_SEQ)
VALUES (17, 3, 'N', 'Y',
   'SEED',          'ACTIVITY_TYPE',         'FUNDS_FRB', 'Unknown', 3);
