CREATE TABLE SAMPLE_DATA.dbo.FRAUD_INTAKE_MASTER (
  FRAUD_INTAKE_ID bigint IDENTITY (1, 1) NOT NULL PRIMARY KEY,
  IS_SEED  varchar(4) NULL,
  IS_ENABLED varchar(4) NULL,
  AUDIT_ID varchar(200) NULL,
  CREATION_DATE datetime NOT NULL,
  ATTRIBUTE1 varchar(100) NULL,
  ATTRIBUTE2 varchar(100) NULL,
  ATTRIBUTE3 varchar(100) NULL,
  ATTRIBUTE4 varchar(100) NULL,
  ATTRIBUTE5 varchar(100) NULL
);

CREATE TABLE SAMPLE_DATA.dbo.FRAUD_INTAKE_REF (
  INTAKE_REF_ID bigint IDENTITY (1, 1) NOT NULL PRIMARY KEY,
  PARENT_ID bigint NULL,
  CHILD_ID bigint NULL,
  IS_PARENT varchar(4) NULL,
  IS_CHILD varchar(4) NULL,
  PARENT_ITEM_TYPE varchar(50) NULL,
  CHILD_ITEM_TYPE varchar(50) NULL,
  PARAM_NAME varchar(100) NULL,
  PARAM_VALUE varchar(200) NULL,
  PARAM_VALUE1 varchar(200) NULL,
  PARAM_VALUE2 varchar(200) NULL,
  PARAM_VALUE3 varchar(200) NULL,
  PARAM_VALUE4 varchar(200) NULL,
  PARAM_VALUE5 varchar(200) NULL,
  IS_MULTI varchar(4) NULL,
  INDEX_SEQ tinyint NULL,
  IS_SEED varchar(4) NULL,
  IS_ENABLED varchar(4) NULL
);

CREATE TABLE SAMPLE_DATA.dbo.FRAUD_INTAKE_FILES (
  INTAKE_FILE_ID bigint IDENTITY (1, 1) NOT NULL PRIMARY KEY,
  INTAKE_REF_ID bigint NULL,
  FILE_NAME varchar(200) NULL,
  FILE_CONTENT varbinary(2000),
  ATTRIBUTE1 varchar(100) NULL,
  ATTRIBUTE2 varchar(100) NULL,
  ATTRIBUTE3 varchar(100) NULL,
  ATTRIBUTE4 varchar(100) NULL,
  ATTRIBUTE5 varchar(100) NULL
);



INSERT INTO SAMPLE_DATA.dbo.FRAUD_INTAKE_MASTER( IS_SEED, IS_ENABLED, AUDIT_ID, CREATION_DATE) 
VALUES ('Y', 'Y', -1, GETDATE());
