CREATE TABLE SAMPLE_DATA.dbo.FRAUD_INTAKE_MASTER (
  FRAUD_INTAKE_ID bigint IDENTITY (1, 1) NOT NULL PRIMARY KEY,
  REPORTING_USER_ID varchar(200) NOT NULL,
  REPORTING_DT datetime NOT NULL,
  REPORT_TYPE varchar(200),
  FRAUD_TYPE_CD varchar(200),
  SUBJECT_NM varchar(200),
  SUBJECT_TYPE_CD varchar(200),
  SUBJECT_TAX_ID varchar(200),
  CUSTOMER_ID varchar(200),
  IMPACT_ACCOUNT_NAME varchar(200),
  CUST_TYPE_CD varchar(200),
  ACCT_TAKEOVER_IN varchar(200),
  ID_THEFT_RELATED_IN varchar(200),
  EVENT_DETAIL_DESC varchar(200),
  ELDER_EXPLOIT_IN varchar(200),
  REFERRAL_REPORTED_BY varchar(200) NOT NULL,
  REFERRAL_DEPT_NM varchar(200) NULL,
  MATTER_IDENTIFIED_CD varchar(200) NULL,
  ATTACHMENT varbinary(2000),
  AUDIT_ID varchar(200) NULL,
  AUDIT_UPDT_TS datetime NOT NULL
);

CREATE TABLE SAMPLE_DATA.dbo.FRAUD_INTAKE_ACTIVITY (
  FRAUD_ACTIVITY_ID bigint IDENTITY (1, 1) NOT NULL PRIMARY KEY,
  FRAUD_INTAKE_ID bigint NOT NULL,
  PRODUCT_TYPE varchar(200) NOT NULL,
  ACCOUNT varchar(200) NOT NULL,
  ACCOUNT_TITILE varchar(200) NOT NULL,
  ACCOUNT_TYPE varchar(200) NOT NULL,
  TRANSACTION_AMOUNT varchar(200) NOT NULL,
  FRAUD_TRANSACTION_DT datetime NOT NULL,
  FUNDS_FRB varchar(200) NOT NULL,
  CLIENT_INIT_TRANSACTION varchar(200) NOT NULL,
  TRANSACTION_IDENTIFIED varchar(200) NOT NULL,
  TRANSACTION_RECALL varchar(200) NOT NULL
);



CREATE TABLE SAMPLE_DATA.dbo.FRAUD_INTAKE_SUBJECT (
  FRAUD_SUBJECT_ID bigint IDENTITY (1, 1) NOT NULL PRIMARY KEY,
  FRAUD_INTAKE_ID bigint NOT NULL,
  SUBJECT_TYPE varchar(200) NOT NULL,
  NETWORK_ID varchar(200) NOT NULL,
  SUBJECT_NM varchar(200) NOT NULL,
  OFFICE_NM varchar(200) NOT NULL,
  SUBJECT_DEP varchar(200) NOT NULL,
  REGION varchar(200) NOT NULL,
  MANGER_NM varchar(200) NOT NULL,
  HR_PARTERNER_NM varchar(200) NOT NULL,
  EMP_INITIAL varchar(200) NOT NULL,
  TRANSACTION_RECALL varchar(200) NOT NULL
);



CREATE TABLE SAMPLE_DATA.dbo.FRAUD_INTAKE_CODES (
FRAUD_REF_CD  varchar(200) NOT NULL,
FRAUD_REF_TYPE varchar(200) NOT NULL,
UI_CONTROL_OPTION_CD varchar(200) NOT NULL,
FRAUD_REF_DESC varchar(200) NOT NULL,
AUDIT_USER_ID varchar(200) NOT NULL,
AUDIT_DT varchar(200) NOT NULL
);

CREATE TABLE SAMPLE_DATA.dbo.FRAUD_INTAKE_VALID_VALUES (
FRAUD_REF_CD  varchar(200) NOT NULL,
FRAUD_REF_VALUE_ID varchar(200) NOT NULL,
FRAUD_REF_VALUE_CD varchar(200) NOT NULL,
FRAUD_REF_VALUE_DESC varchar(200) NOT NULL,
AUDIT_USER_ID varchar(200) NOT NULL,
AUDIT_DT varchar(200) NOT NULL
);

